version : "3.5"
services:
  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    # environment:
    #   ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
    #   ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
    command: >
      etcd
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
    volumes:
      - ./volumes/etcd:/etcd-data
    ports:
      - "2379:2379"

  milvus-minio:
    image: minio/minio:RELEASE.2023-08-04T17-40-21Z
    container_name: milvus-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./volumes/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  milvus-standalone:
    image: milvusdb/milvus:v2.6.0
    container_name: milvus-standalone
    depends_on:
      - milvus-etcd
      - milvus-minio
    ports:
      - "19530:19530"   # gRPC
      - "9191:9091"     # REST API mapped to avoid host conflict
    environment:
      ETCD_ENDPOINTS: milvus-etcd:2379
      MINIO_ADDRESS: milvus-minio:9000
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    command: ["milvus", "run", "standalone"]

